str1=input(print("Enter the string"))
str2=input(print("Enter the string"))
str =(str1+str2)
print(str)
#Used string methods
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.swapcase())
print(str.casefold())
print(str.count("l"))
print(str.center(40))
print(str.startswith("h"))
print(str.expandtabs(tabsize=40))
print(str.find("h"))
print(str.isnumeric())
print(str.isalnum())
print(str.replace("this","Yehh its"))
print(str.rpartition(" "))
str1="Name:\nA\nB\nC\nD"
print("The string before splitting"+str1)
print("The string after:")
print(str1.splitlines())
print(str1.strip())